language: node_js
node_js:
- node
- '5.11'
- '4.4'
- iojs
- '0.12'
matrix:
  fast_finish: true
sudo: false
script:
- npm run ci
before_deploy:
- npm run build
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: huEmPsD+/+XrKVYL2R7HCAdTVovgcMf0reqGvex/BdG/ICksmrFDjE52iasaobdCAQuGbHgOqXaDZuaVxN5MWzQPSCpxSlQYrdAtU26lnGE2mna8hD3NBmR/qD5kgJlW4599fV7yLEwAO9/bmSl0sn36B4lPtXYx5SGByg1ROTPQLvWTTpypo6FysNmmBXg35il3ntS4lkMoSOsHthyClwGkeGhYj+/uqFc3QYyUz54ImvL/Lo9o3mzPp3yautshhzuIe++HY9mxJ9LP8CXLJpDgzgtRhIzYqKb3MmBX44BQQkThE8IxldbkQOtVugGkx6g3rjbowrAR9zHBWxKNVC0giH+vi06QRW/4DHP2eabwNCpbRNQPKaU+Hv6KHUYj/13XH/kJixvrQ+seHqJi6z89yVZJGVZh8hSBeNBbrxRVxJn69Wc8Paf+b3soDvX1VOx3Z5xxcR3sZ4dqrG2anmlgiGHTgb0Xgjn72KArR/J2FAWUcDdH/VGpCYboEDkh9jC4x6F01hEtfwAxYdxUTwSOCN5ycf0RY+UkQF7eUlCbJVJqpZZxW/EPQtASMYEZjU7h65fgmwKtAHna9YQHEVn77DGXusavZ5VjFnbo8VkHL+IJNbWzT/nwWZYH8BxYF7TU3dAaRy66fvGlTV5kZMqSIkalVCKb6v4pboN9hls=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-mongodb
