language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
matrix:
  fast_finish: true
before_install:
- npm install -g grunt-cli
script:
- grunt ci
- grunt coveralls:push
env:
  matrix:
  - secure: OMJ9PJyQ6vZnOBYpNxjvOvWB//DwhbUjVg7gOtbKUkZxiGrOletCnu0gm1Zt4Jh85Q8LcpZ/rDRuYVC/YLxKPsRW5vCwWfdT5ctYa350+l2KnBN6qRB3D/NP2N+YegFfTAGMA+cVS0E8Hv27aHgED3hs0XTMmwtWPmwx+0ki712XS4rSa9jGxDcioPwXbSmYpRt/2n1zh0d2pC9Wy3j2WH7CnwMFTDq8/hZAL7cLvngMlcI7Sxuox2PPqwoAHSdGOiGULaPFo8iYyqO9kNshKaHEolMbaLl9Pc/kV7pj8t4+r8kMe+cPYD2pMWVW3ZOeKAM//lEhBS+qK7FbWddD3RufQVysIZvvlnThXDJ80LhXyA4hyknXlxAgudsiZLEgWZizh7de8rTxC3ZGnwE+zEo9QWOYmR4dYU0127VxOJLhz+GnMPZ58Csj+XgzBpcKW/AM0S4FxMhv+z6WUYdLxCNkwK9Dzf7/lCPS8PDSURAp0aYmuWqBVvAk89Zvg5M42xaF3CR9BpzwpYdWdwVyf956ntukbX2FuGC0RdNZgiR4V8ptuuJxj5Zh0+e51QrD+Nn38oFERonDOPhib2s7p+2OalcKhS1fO/eSqcSTxYfklTKWC0SPBebNlZoJ2VwXhoo8EErAoeFNqaGOVOmkdOhM1JphBne5Bitl/QF0ZDQ=
  - secure: VFWahf4mUR7o3PBRYniGcXGR8BYD1R1e/z8wQsAOUVD6+fj/lLvFwtYCYKrzPhPOiQH3k4YBOeLE3OJpnz25VdBEbvaBpkZsoPwy1PBzSaX/7o1dtvZxdgIJ58wdvG4rV9nEUj2W/h2EqqTYDwG72yZb9lBg1mgA7xVFStNbKSPpGz2qP+YKPgBHbs+YGOinwHwYhkYADPG6rBrjCmNly0w7l7XUIdGDRNcvAFzhwVrpk/6yWI1snARvb7KMLmOiJxXp/k313X6IBnjzka2BYK80TtATgblSd5MeHDuRKVol+aU1upfFZ7+KB4zipMU0gSMJONWDayGvXaGX/V84NkovhEQVjAYXExGK4MUV+G2nx5a9dmQkz+iP8DZ5mqc6QoPssQQlwII0QCVXlrJHcQjdAmGl6xmgketsRKdsLAClapBEgaLO5qxhbQ6x3ldD4lkF5r30uSPHo1tNhZvYmes7hBpiEG4VoEZ4NSluYkKJONp58tHEExweLY/6q0R11xl5+lqYyfhdhwPELZQfF+cPG4VoVb6AUKPm/KSSD9VVavg0Cib6AkOfXL5en2rbVYkd2wJ5sC4X8fTl6BS81iVmXQY3CwWV+bZYDmSpuzcdT9eVZzgRtcbkkPuWqtFNAdSdcIX6AMZdMsiTYBEqIcGIsNdj1dsWHg529pk2RGc=
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: S2Bi4AxnWHADdeLWrRTmfMz80vjAkEIjCDeMzIXVmrc+9c6Rl4v1vi+X8ZE7h11t954a4pSoi0RPwGMTErqe74TcSB42bcojDnzjIOCszlTQ2urqN3EuSSq7hupJEIxBovzIofzQgxEtmPg2JQd2Yq1SNWo1iw65s3HK10hcxwn6cNZrlXdo+0aGSDYjH/GDTnQFKouMsTmM2BaeimWAzFlumUvKWTr82o/uTEr5LAtS9Z4mo7yHKezt2ySYpbEvKJXFh+T4P8KS09DXkumU0p4SdSZaR4U3F2DtXpQrrsZi6sZTspiE+xwxgUSaXIraZbhHGYptLSyQvaSnd0d47BQBuhFGiVFluIeyzOY3iOh6nPggslEvVEgdz2VxFrDsrKZ5ENt6VH0e6Twwkc4EbaPC4v/FXTi6XEq0EWBIXT1nxLxXiKqNAyM8SBWkwNLVZE8tb9F6DqUBSAm5ieZ2k/Fof4G8E22EkEfW+/dzyZRQofPbp0tuUjz4PbPZt+pQOviFSvpRUWon7rze7GxxqC81Xu6obv6kIk298n9E8lKnycc5kvFQCX66PuPo1s8b8+Vc1R2JPSrndm6IA5eL4k/lhTjkWXv/R+zvI1e31EpPRMDlsHdA/I8BglQM2VO9fgWYGmCjYOyyRp30jC++KCMHcK0abCvF6OoYnjzNqls=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-mongogodb
