language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
matrix:
  fast_finish: true
before_install:
- npm install -g grunt-cli
script:
- grunt ci
- grunt coveralls:push
env:
  matrix:
    secure: ZKZhtx+CHjHuCoJZqTHu0KHPf/k6urQj5H+eNszvU3BtY3dKKryMuraTWXLdN5i9Is91/AlW6tDxMNq9jK8EXXgZttbaxtptIjRksCQITXD6mQFmW5JHSDIzd5z1g6xbd7W4SAfkyBpW5JzwrwJx9Jb3Idca4vMbeKpOM8GbGgJ0lryrFM0Cq9ZvMiwgVW31tOKgqPylgYcVZmwWN0zOLmTHst1oI/uvpYbuAgkuTQfT+U28mtai7vYkqgJtJnIIPA3UkkhPiYO6RxsfpnZA2Y6zjb2+S09Gzz3xUn63iLhmIU9VPvM8El9dmjeEPD/E9GejuZUDJ1/JLUUWrrz19/Oi3MYsdSo915XPfJmoFUPQsOBGBCRHAJmqLkJqCa9drfLZqRhXWaVsycos798QX0fF5pWEZaLV9julfddSXeKndFz7MphMWa6ho/c4urpdJyeHlz6l1AyssI9fZl+Zf3h/6+3NTNo3fC2Pf8+uhL6x8HMM+eNr2MNw6gTwm+X4CWCgqEkt3jhOk92QtrH2JI1Ba97dfr2svYsmeaMgEZ0mUC1qMrrjm9bQLPdJohEDFDVjg9ZqfxEk6Vu1umeKoY40zQYAEgt6EBlgsR2wUWmULIzKrw6r7ThZvWqkyfwN8LXbvp3Ne/FFufURin+SH8C9xgfZU98GzMZU/SX6vKA=
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: S2Bi4AxnWHADdeLWrRTmfMz80vjAkEIjCDeMzIXVmrc+9c6Rl4v1vi+X8ZE7h11t954a4pSoi0RPwGMTErqe74TcSB42bcojDnzjIOCszlTQ2urqN3EuSSq7hupJEIxBovzIofzQgxEtmPg2JQd2Yq1SNWo1iw65s3HK10hcxwn6cNZrlXdo+0aGSDYjH/GDTnQFKouMsTmM2BaeimWAzFlumUvKWTr82o/uTEr5LAtS9Z4mo7yHKezt2ySYpbEvKJXFh+T4P8KS09DXkumU0p4SdSZaR4U3F2DtXpQrrsZi6sZTspiE+xwxgUSaXIraZbhHGYptLSyQvaSnd0d47BQBuhFGiVFluIeyzOY3iOh6nPggslEvVEgdz2VxFrDsrKZ5ENt6VH0e6Twwkc4EbaPC4v/FXTi6XEq0EWBIXT1nxLxXiKqNAyM8SBWkwNLVZE8tb9F6DqUBSAm5ieZ2k/Fof4G8E22EkEfW+/dzyZRQofPbp0tuUjz4PbPZt+pQOviFSvpRUWon7rze7GxxqC81Xu6obv6kIk298n9E8lKnycc5kvFQCX66PuPo1s8b8+Vc1R2JPSrndm6IA5eL4k/lhTjkWXv/R+zvI1e31EpPRMDlsHdA/I8BglQM2VO9fgWYGmCjYOyyRp30jC++KCMHcK0abCvF6OoYnjzNqls=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-mongogodb
